<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            // ✅ دول الخليج أولاً
            ['name' => json_encode(['ar' => 'البحرين', 'en' => 'Bahrain']), 'phone_code' => '973', 'image_path' => 'flags/bahrain.svg'],
            ['name' => json_encode(['ar' => 'المملكة العربية السعودية', 'en' => 'Saudi Arabia']), 'phone_code' => '966', 'image_path' => 'flags/saudi-arabia.svg'],
            ['name' => json_encode(['ar' => 'الإمارات العربية المتحدة', 'en' => 'United Arab Emirates']), 'phone_code' => '971', 'image_path' => 'flags/united-arab-emirates.svg'],
            ['name' => json_encode(['ar' => 'الكويت', 'en' => 'Kuwait']), 'phone_code' => '965', 'image_path' => 'flags/kuwait.svg'],
            ['name' => json_encode(['ar' => 'قطر', 'en' => 'Qatar']), 'phone_code' => '974', 'image_path' => 'flags/qatar.svg'],
            ['name' => json_encode(['ar' => 'عُمان', 'en' => 'Oman']), 'phone_code' => '968', 'image_path' => 'flags/oman.svg'],
            ['name' => json_encode(['ar' => 'أفغانستان', 'en' => 'Afghanistan']), 'phone_code' => '93', 'image_path' => 'flags/afghanistan.svg'],
            ['name' => json_encode(['ar' => 'ألبانيا', 'en' => 'Albania']), 'phone_code' => '355', 'image_path' => 'flags/albania.svg'],
            ['name' => json_encode(['ar' => 'الجزائر', 'en' => 'Algeria']), 'phone_code' => '213', 'image_path' => 'flags/algeria.svg'],
            ['name' => json_encode(['ar' => 'أندورا', 'en' => 'Andorra']), 'phone_code' => '376', 'image_path' => 'flags/andorra.svg'],
            ['name' => json_encode(['ar' => 'أنغولا', 'en' => 'Angola']), 'phone_code' => '244', 'image_path' => 'flags/angola.svg'],
            ['name' => json_encode(['ar' => 'الأرجنتين', 'en' => 'Argentina']), 'phone_code' => '54', 'image_path' => 'flags/argentina.svg'],
            ['name' => json_encode(['ar' => 'أرمينيا', 'en' => 'Armenia']), 'phone_code' => '374', 'image_path' => 'flags/armenia.svg'],
            ['name' => json_encode(['ar' => 'أستراليا', 'en' => 'Australia']), 'phone_code' => '61', 'image_path' => 'flags/australia.svg'],
            ['name' => json_encode(['ar' => 'النمسا', 'en' => 'Austria']), 'phone_code' => '43', 'image_path' => 'flags/austria.svg'],
            ['name' => json_encode(['ar' => 'أذربيجان', 'en' => 'Azerbaijan']), 'phone_code' => '994', 'image_path' => 'flags/azerbaijan.svg'],
            ['name' => json_encode(['ar' => 'بنغلاديش', 'en' => 'Bangladesh']), 'phone_code' => '880', 'image_path' => 'flags/bangladesh.svg'],
            ['name' => json_encode(['ar' => 'بيلاروسيا', 'en' => 'Belarus']), 'phone_code' => '375', 'image_path' => 'flags/belarus.svg'],
            ['name' => json_encode(['ar' => 'بلجيكا', 'en' => 'Belgium']), 'phone_code' => '32', 'image_path' => 'flags/belgium.svg'],
            ['name' => json_encode(['ar' => 'بوليفيا', 'en' => 'Bolivia']), 'phone_code' => '591', 'image_path' => 'flags/bolivia.svg'],
            ['name' => json_encode(['ar' => 'البوسنة والهرسك', 'en' => 'Bosnia and Herzegovina']), 'phone_code' => '387', 'image_path' => 'flags/bosnia-and-herzegovina.svg'],
            ['name' => json_encode(['ar' => 'البرازيل', 'en' => 'Brazil']), 'phone_code' => '55', 'image_path' => 'flags/brazil.svg'],
            ['name' => json_encode(['ar' => 'بلغاريا', 'en' => 'Bulgaria']), 'phone_code' => '359', 'image_path' => 'flags/bulgaria.svg'],
            ['name' => json_encode(['ar' => 'كمبوديا', 'en' => 'Cambodia']), 'phone_code' => '855', 'image_path' => 'flags/cambodia.svg'],
            ['name' => json_encode(['ar' => 'الكاميرون', 'en' => 'Cameroon']), 'phone_code' => '237', 'image_path' => 'flags/cameroon.svg'],
            ['name' => json_encode(['ar' => 'كندا', 'en' => 'Canada']), 'phone_code' => '1', 'image_path' => 'flags/canada.svg'],
            ['name' => json_encode(['ar' => 'تشيلي', 'en' => 'Chile']), 'phone_code' => '56', 'image_path' => 'flags/chile.svg'],
            ['name' => json_encode(['ar' => 'الصين', 'en' => 'China']), 'phone_code' => '86', 'image_path' => 'flags/china.svg'],
            ['name' => json_encode(['ar' => 'كولومبيا', 'en' => 'Colombia']), 'phone_code' => '57', 'image_path' => 'flags/colombia.svg'],
            ['name' => json_encode(['ar' => 'كرواتيا', 'en' => 'Croatia']), 'phone_code' => '385', 'image_path' => 'flags/croatia.svg'],
            ['name' => json_encode(['ar' => 'كوبا', 'en' => 'Cuba']), 'phone_code' => '53', 'image_path' => 'flags/cuba.svg'],
            ['name' => json_encode(['ar' => 'قبرص', 'en' => 'Cyprus']), 'phone_code' => '357', 'image_path' => 'flags/cyprus.svg'],
            ['name' => json_encode(['ar' => 'التشيك', 'en' => 'Czech Republic']), 'phone_code' => '420', 'image_path' => 'flags/czech-republic.svg'],
            ['name' => json_encode(['ar' => 'الدنمارك', 'en' => 'Denmark']), 'phone_code' => '45', 'image_path' => 'flags/denmark.svg'],
            ['name' => json_encode(['ar' => 'الإكوادور', 'en' => 'Ecuador']), 'phone_code' => '593', 'image_path' => 'flags/ecuador.svg'],
            ['name' => json_encode(['ar' => 'مصر', 'en' => 'Egypt']), 'phone_code' => '20', 'image_path' => 'flags/egypt.svg'],
            ['name' => json_encode(['ar' => 'إثيوبيا', 'en' => 'Ethiopia']), 'phone_code' => '251', 'image_path' => 'flags/ethiopia.svg'],
            ['name' => json_encode(['ar' => 'فنلندا', 'en' => 'Finland']), 'phone_code' => '358', 'image_path' => 'flags/finland.svg'],
            ['name' => json_encode(['ar' => 'فرنسا', 'en' => 'France']), 'phone_code' => '33', 'image_path' => 'flags/france.svg'],
            ['name' => json_encode(['ar' => 'جورجيا', 'en' => 'Georgia']), 'phone_code' => '995', 'image_path' => 'flags/georgia.svg'],
            ['name' => json_encode(['ar' => 'ألمانيا', 'en' => 'Germany']), 'phone_code' => '49', 'image_path' => 'flags/germany.svg'],
            ['name' => json_encode(['ar' => 'غانا', 'en' => 'Ghana']), 'phone_code' => '233', 'image_path' => 'flags/ghana.svg'],
            ['name' => json_encode(['ar' => 'اليونان', 'en' => 'Greece']), 'phone_code' => '30', 'image_path' => 'flags/greece.svg'],
            ['name' => json_encode(['ar' => 'غواتيمالا', 'en' => 'Guatemala']), 'phone_code' => '502', 'image_path' => 'flags/guatemala.svg'],
            ['name' => json_encode(['ar' => 'المجر', 'en' => 'Hungary']), 'phone_code' => '36', 'image_path' => 'flags/hungary.svg'],
            ['name' => json_encode(['ar' => 'الهند', 'en' => 'India']), 'phone_code' => '91', 'image_path' => 'flags/india.svg'],
            ['name' => json_encode(['ar' => 'إندونيسيا', 'en' => 'Indonesia']), 'phone_code' => '62', 'image_path' => 'flags/indonesia.svg'],
            ['name' => json_encode(['ar' => 'إيران', 'en' => 'Iran']), 'phone_code' => '98', 'image_path' => 'flags/iran.svg'],
            ['name' => json_encode(['ar' => 'العراق', 'en' => 'Iraq']), 'phone_code' => '964', 'image_path' => 'flags/iraq.svg'],
            ['name' => json_encode(['ar' => 'أيرلندا', 'en' => 'Ireland']), 'phone_code' => '353', 'image_path' => 'flags/ireland.svg'],
            ['name' => json_encode(['ar' => 'إيطاليا', 'en' => 'Italy']), 'phone_code' => '39', 'image_path' => 'flags/italy.svg'],
            ['name' => json_encode(['ar' => 'اليابان', 'en' => 'Japan']), 'phone_code' => '81', 'image_path' => 'flags/japan.svg'],
            ['name' => json_encode(['ar' => 'الأردن', 'en' => 'Jordan']), 'phone_code' => '962', 'image_path' => 'flags/jordan.svg'],
            ['name' => json_encode(['ar' => 'كازاخستان', 'en' => 'Kazakhstan']), 'phone_code' => '7', 'image_path' => 'flags/kazakhstan.svg'],
            ['name' => json_encode(['ar' => 'كينيا', 'en' => 'Kenya']), 'phone_code' => '254', 'image_path' => 'flags/kenya.svg'],
            ['name' => json_encode(['ar' => 'قيرغيزستان', 'en' => 'Kyrgyzstan']), 'phone_code' => '996', 'image_path' => 'flags/kyrgyzstan.svg'],
            ['name' => json_encode(['ar' => 'لبنان', 'en' => 'Lebanon']), 'phone_code' => '961', 'image_path' => 'flags/lebanon.svg'],
            ['name' => json_encode(['ar' => 'ليبيا', 'en' => 'Libya']), 'phone_code' => '218', 'image_path' => 'flags/libya.svg'],
            ['name' => json_encode(['ar' => 'ماليزيا', 'en' => 'Malaysia']), 'phone_code' => '60', 'image_path' => 'flags/malaysia.svg'],
            ['name' => json_encode(['ar' => 'المالديف', 'en' => 'Maldives']), 'phone_code' => '960', 'image_path' => 'flags/maldives.svg'],
            ['name' => json_encode(['ar' => 'مالي', 'en' => 'Mali']), 'phone_code' => '223', 'image_path' => 'flags/mali.svg'],
            ['name' => json_encode(['ar' => 'مالطا', 'en' => 'Malta']), 'phone_code' => '356', 'image_path' => 'flags/malta.svg'],
            ['name' => json_encode(['ar' => 'موريتانيا', 'en' => 'Mauritania']), 'phone_code' => '222', 'image_path' => 'flags/mauritania.svg'],
            ['name' => json_encode(['ar' => 'المكسيك', 'en' => 'Mexico']), 'phone_code' => '52', 'image_path' => 'flags/mexico.svg'],
            ['name' => json_encode(['ar' => 'مولدوفا', 'en' => 'Moldova']), 'phone_code' => '373', 'image_path' => 'flags/moldova.svg'],
            ['name' => json_encode(['ar' => 'منغوليا', 'en' => 'Mongolia']), 'phone_code' => '976', 'image_path' => 'flags/mongolia.svg'],
            ['name' => json_encode(['ar' => 'المغرب', 'en' => 'Morocco']), 'phone_code' => '212', 'image_path' => 'flags/morocco.svg'],
            ['name' => json_encode(['ar' => 'موزمبيق', 'en' => 'Mozambique']), 'phone_code' => '258', 'image_path' => 'flags/mozambique.svg'],
            ['name' => json_encode(['ar' => 'ميانمار', 'en' => 'Myanmar']), 'phone_code' => '95', 'image_path' => 'flags/myanmar.svg'],
            ['name' => json_encode(['ar' => 'نيبال', 'en' => 'Nepal']), 'phone_code' => '977', 'image_path' => 'flags/nepal.svg'],
            ['name' => json_encode(['ar' => 'هولندا', 'en' => 'Netherlands']), 'phone_code' => '31', 'image_path' => 'flags/netherlands.svg'],
            ['name' => json_encode(['ar' => 'نيوزيلندا', 'en' => 'New Zealand']), 'phone_code' => '64', 'image_path' => 'flags/new-zealand.svg'],
            ['name' => json_encode(['ar' => 'نيجيريا', 'en' => 'Nigeria']), 'phone_code' => '234', 'image_path' => 'flags/nigeria.svg'],
            ['name' => json_encode(['ar' => 'النرويج', 'en' => 'Norway']), 'phone_code' => '47', 'image_path' => 'flags/norway.svg'],
            ['name' => json_encode(['ar' => 'باكستان', 'en' => 'Pakistan']), 'phone_code' => '92', 'image_path' => 'flags/pakistan.svg'],
            ['name' => json_encode(['ar' => 'فلسطين', 'en' => 'Palestine']), 'phone_code' => '970', 'image_path' => 'flags/palestine.svg'],
            ['name' => json_encode(['ar' => 'بنما', 'en' => 'Panama']), 'phone_code' => '507', 'image_path' => 'flags/panama.svg'],
            ['name' => json_encode(['ar' => 'بيرو', 'en' => 'Peru']), 'phone_code' => '51', 'image_path' => 'flags/peru.svg'],
            ['name' => json_encode(['ar' => 'الفلبين', 'en' => 'Philippines']), 'phone_code' => '63', 'image_path' => 'flags/philippines.svg'],
            ['name' => json_encode(['ar' => 'بولندا', 'en' => 'Poland']), 'phone_code' => '48', 'image_path' => 'flags/poland.svg'],
            ['name' => json_encode(['ar' => 'البرتغال', 'en' => 'Portugal']), 'phone_code' => '351', 'image_path' => 'flags/portugal.svg'],
            ['name' => json_encode(['ar' => 'رومانيا', 'en' => 'Romania']), 'phone_code' => '40', 'image_path' => 'flags/romania.svg'],
            ['name' => json_encode(['ar' => 'روسيا', 'en' => 'Russia']), 'phone_code' => '7', 'image_path' => 'flags/russia.svg'],
            ['name' => json_encode(['ar' => 'السنغال', 'en' => 'Senegal']), 'phone_code' => '221', 'image_path' => 'flags/senegal.svg'],
            ['name' => json_encode(['ar' => 'صربيا', 'en' => 'Serbia']), 'phone_code' => '381', 'image_path' => 'flags/serbia.svg'],
            ['name' => json_encode(['ar' => 'سنغافورة', 'en' => 'Singapore']), 'phone_code' => '65', 'image_path' => 'flags/singapore.svg'],
            ['name' => json_encode(['ar' => 'سلوفاكيا', 'en' => 'Slovakia']), 'phone_code' => '421', 'image_path' => 'flags/slovakia.svg'],
            ['name' => json_encode(['ar' => 'الصومال', 'en' => 'Somalia']), 'phone_code' => '252', 'image_path' => 'flags/somalia.svg'],
            ['name' => json_encode(['ar' => 'جنوب أفريقيا', 'en' => 'South Africa']), 'phone_code' => '27', 'image_path' => 'flags/south-africa.svg'],
            ['name' => json_encode(['ar' => 'كوريا الجنوبية', 'en' => 'South Korea']), 'phone_code' => '82', 'image_path' => 'flags/south-korea.svg'],
            ['name' => json_encode(['ar' => 'إسبانيا', 'en' => 'Spain']), 'phone_code' => '34', 'image_path' => 'flags/spain.svg'],
            ['name' => json_encode(['ar' => 'سريلانكا', 'en' => 'Sri Lanka']), 'phone_code' => '94', 'image_path' => 'flags/sri-lanka.svg'],
            ['name' => json_encode(['ar' => 'السودان', 'en' => 'Sudan']), 'phone_code' => '249', 'image_path' => 'flags/sudan.svg'],
            ['name' => json_encode(['ar' => 'السويد', 'en' => 'Sweden']), 'phone_code' => '46', 'image_path' => 'flags/sweden.svg'],
            ['name' => json_encode(['ar' => 'سويسرا', 'en' => 'Switzerland']), 'phone_code' => '41', 'image_path' => 'flags/switzerland.svg'],
            ['name' => json_encode(['ar' => 'سوريا', 'en' => 'Syria']), 'phone_code' => '963', 'image_path' => 'flags/syria.svg'],
            ['name' => json_encode(['ar' => 'تايوان', 'en' => 'Taiwan']), 'phone_code' => '886', 'image_path' => 'flags/taiwan.svg'],
            ['name' => json_encode(['ar' => 'طاجيكستان', 'en' => 'Tajikistan']), 'phone_code' => '992', 'image_path' => 'flags/tajikistan.svg'],
            ['name' => json_encode(['ar' => 'تنزانيا', 'en' => 'Tanzania']), 'phone_code' => '255', 'image_path' => 'flags/tanzania.svg'],
            ['name' => json_encode(['ar' => 'تايلاند', 'en' => 'Thailand']), 'phone_code' => '66', 'image_path' => 'flags/thailand.svg'],
            ['name' => json_encode(['ar' => 'تونس', 'en' => 'Tunisia']), 'phone_code' => '216', 'image_path' => 'flags/tunisia.svg'],
            ['name' => json_encode(['ar' => 'تركيا', 'en' => 'Turkey']), 'phone_code' => '90', 'image_path' => 'flags/turkey.svg'],
            ['name' => json_encode(['ar' => 'تركمانستان', 'en' => 'Turkmenistan']), 'phone_code' => '993', 'image_path' => 'flags/turkmenistan.svg'],
            ['name' => json_encode(['ar' => 'أوغندا', 'en' => 'Uganda']), 'phone_code' => '256', 'image_path' => 'flags/uganda.svg'],
            ['name' => json_encode(['ar' => 'أوكرانيا', 'en' => 'Ukraine']), 'phone_code' => '380', 'image_path' => 'flags/ukraine.svg'],
            ['name' => json_encode(['ar' => 'المملكة المتحدة', 'en' => 'United Kingdom']), 'phone_code' => '44', 'image_path' => 'flags/united-kingdom.svg'],
            ['name' => json_encode(['ar' => 'الولايات المتحدة', 'en' => 'United States']), 'phone_code' => '1', 'image_path' => 'flags/united-states.svg'],
            ['name' => json_encode(['ar' => 'أوروغواي', 'en' => 'Uruguay']), 'phone_code' => '598', 'image_path' => 'flags/uruguay.svg'],
            ['name' => json_encode(['ar' => 'أوزبكستان', 'en' => 'Uzbekistan']), 'phone_code' => '998', 'image_path' => 'flags/uzbekistan.svg'],
            ['name' => json_encode(['ar' => 'فنزويلا', 'en' => 'Venezuela']), 'phone_code' => '58', 'image_path' => 'flags/venezuela.svg'],
            ['name' => json_encode(['ar' => 'فيتنام', 'en' => 'Vietnam']), 'phone_code' => '84', 'image_path' => 'flags/vietnam.svg'],
            ['name' => json_encode(['ar' => 'اليمن', 'en' => 'Yemen']), 'phone_code' => '967', 'image_path' => 'flags/yemen.svg'],
            ['name' => json_encode(['ar' => 'زامبيا', 'en' => 'Zambia']), 'phone_code' => '260', 'image_path' => 'flags/zambia.svg'],
            ['name' => json_encode(['ar' => 'زيمبابوي', 'en' => 'Zimbabwe']), 'phone_code' => '263', 'image_path' => 'flags/zimbabwe.svg'],
        ];

        DB::table('countries')->insertOrIgnore($countries);
    }
}
